language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install codecov coverage graphviz

script:
  - coverage run runtests.py
  - coverage report

after_success:
  - codecov
  - coveralls